/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'csteinba' at '9/18/14 2:24 PM' with Gradle 2.0
 *
 * @author csteinba, @date 9/18/14 2:24 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
